#!/usr/bin/env python3

import random
from pathlib import Path

ADJECTIVES = [
    "amber",
    "brave",
    "brisk",
    "calm",
    "clever",
    "cosy",
    "crisp",
    "curly",
    "dapper",
    "dizzy",
    "eager",
    "fancy",
    "fluffy",
    "frosty",
    "fuzzy",
    "gentle",
    "giddy",
    "glossy",
    "grumpy",
    "hasty",
    "jolly",
    "lanky",
    "lucky",
    "mellow",
    "merry",
    "misty",
    "nimble",
    "noisy",
    "plucky",
    "quiet",
    "rapid",
    "rusty",
    "shiny",
    "silly",
    "sleepy",
    "snappy",
    "soggy",
    "spicy",
    "squishy",
    "stormy",
    "sunny",
    "tidy",
    "tiny",
    "wobbly",
]

BIRDS = [
    "albatross",
    "avocet",
    "bittern",
    "bunting",
    "buzzard",
    "chaffinch",
    "chickadee",
    "cormorant",
    "crane",
    "crow",
    "cuckoo",
    "curlew",
    "dipper",
    "dove",
    "dunlin",
    "eagle",
    "egret",
    "falcon",
    "finch",
    "flamingo",
    "gannet",
    "goldfinch",
    "goose",
    "grebe",
    "grouse",
    "gull",
    "harrier",
    "hawk",
    "heron",
    "hoopoe",
    "ibis",
    "jackdaw",
    "jay",
    "kestrel",
    "kingfisher",
    "kite",
    "kiwi",
    "lapwing",
    "lark",
    "magpie",
    "mallard",
    "merlin",
    "nightingale",
    "nuthatch",
    "oriole",
    "osprey",
    "ostrich",
    "owl",
    "parakeet",
    "partridge",
    "pelican",
    "penguin",
    "pheasant",
    "pigeon",
    "plover",
    "puffin",
    "quail",
    "raven",
    "redstart",
    "robin",
    "rook",
    "sandpiper",
    "shrike",
    "siskin",
    "skylark",
    "snipe",
    "sparrow",
    "starling",
    "stork",
    "swallow",
    "swan",
    "swift",
    "tern",
    "thrush",
    "toucan",
    "warbler",
    "waxwing",
    "woodpecker",
    "wren",
]


def main() -> None:
    used = {p.name for p in Path("data").glob("*/*")}
    while (name := f"{random.choice(ADJECTIVES)}-{random.choice(BIRDS)}") in used:
        pass
    print(name)


if __name__ == "__main__":
    main()
